---
title: "My project"
author: "Rainbow"
date: "2024-10-11"
output: "github_document"
---



```{r}
library(haven)
library(dplyr)
library(tidyr)
library(ggplot2)
library(psych)
library(bruceR)
library(ggsci)
library(see)
library(car)
library(Rmisc)
library(rstatix)
library(emmeans)
library(labelled)
library(ggstatsplot)
library(performance)
library(sjPlot)

dataset <- read.csv("/Users/rainbow/Documents/project\ dataset.csv")

```

#Recode variables
```{r}
dataset <- dataset %>%
  mutate_at(c('gender'),funs(str_replace(., "1", "Men")))

dataset <- dataset %>%
  mutate_at(c('gender'),funs(str_replace(., "2", "Women")))


breaks <- c(20, 40, 50)
labels <- c("Low", "High")
  
dataset$SE_group <- cut(dataset$Self_esteem, breaks = breaks, labels = labels, right = FALSE)

```
#Normality
##Normality plots
```{r}
ggplot(dataset, aes(x = relationship_satis)) + geom_histogram(binwidth = 5) + theme_classic()

ggplot(dataset, aes(x = relationship_satis)) + geom_density(adjust = 2)  + theme_classic()

qq<-ggplot(dataset, aes(sample = relationship_satis)) + geom_qq()  + theme_classic()

qq+ geom_qq_line()
```
###Normality plots by gender
```{r}
ggplot(dataset, aes(x = relationship_satis)) + geom_histogram(binwidth = 5) + theme_classic() + facet_wrap(~gender) + theme_classic()

ggplot(dataset, aes(x = relationship_satis)) + geom_density(adjust = 2)  + theme_classic() + facet_wrap(~gender) + theme_classic()

qq<-ggplot(dataset, aes(sample = relationship_satis)) + geom_qq()  + theme_classic() + facet_wrap(~gender) + theme_classic()

qq+ geom_qq_line()+ facet_wrap(~gender) 
```
##Normality tests
```{r}
describe(dataset$relationship_satis)

shapiro.test(dataset$relationship_satis)

```
### Normality tests by gender
```{r}
?describeBy()

describeBy(relationship_satis ~ gender, data = dataset)

dataset %>%
  group_by(gender) %>%
  summarize(W = shapiro.test(relationship_satis)$statistic, p_value = shapiro.test(relationship_satis)$p.value)

```

# Equal Variance between Groups
## Descrptive Variance
```{r}
data_clean<-drop_na(dataset)

var(data_clean$relationship_satis)

data_clean %>%
  group_by(gender) %>%
  summarize(variance = var(relationship_satis))
```
## Equal Variance Test
```{r}
leveneTest(relationship_satis~gender, data_clean)

MANOVA(data_clean, dv = "relationship_satis", between = "gender")

```
#Summary Descriptive Statistics
```{r}
data_clean %>%
  group_by(gender) %>%
  dplyr::summarize(mean_Self_esteem    = mean(Self_esteem),
      mean_relationship_satis    = mean(relationship_satis),
      std_dev_Self_esteem = sd(Self_esteem),
      std_dev_relationship_satis = sd(relationship_satis),
      corr_Self_esteem_relationship_satis  = cor(Self_esteem, relationship_satis))
```

#ANOVA
##Recode 2x2 into 1x4
```{r}
data_clean$Group <- ifelse(data_clean$gender == "Women" & data_clean$SE_group == "High", "High SE Women", 
                     ifelse(data_clean$gender == "Men" & data_clean$SE_group == "High", "High SE Men", 
                            ifelse(data_clean$gender == "Women" & data_clean$SE_group == "Low", "Low SE Women", 
                                   "Low SE Men")))
```

##contrast coefficients
```{r}
#1st group is High SE Women, 
#2nd group is High SE men, 
#3rd group is Low SE Women,
#4th group is Low SE Men. 

```

##Model and tests
```{r}
mod<-MANOVA(data_clean, dv = "relationship_satis", between = c("gender", "SE_group")) 

EMMEANS(mod, effect = "gender", by = "SE_group", p.adjust = "none")

EMMEANS(mod, effect = "SE_group", by = "gender", p.adjust = "none")
```

##Visualization
```{r}

plot<-summarySE(data_clean, measurevar="relationship_satis", groupvars=c("gender", "SE_group"))

plot

plot2<-summarySE(data_clean, measurevar="relationship_satis", groupvars=c("Group"))

plot2

ggplot(plot, aes(x = SE_group, y = relationship_satis, fill = SE_group)) +
  geom_col() + facet_wrap(~ gender) + theme_bruce()

ggplot(plot2, aes(x = Group, y = relationship_satis, fill = Group)) +
  geom_col()  + theme_bruce() + theme(axis.text.x = element_text(angle = -10))
```
#Regression 
##Correlation
```{r}
regression <- data_clean %>%
  select(power, authenticity, Self_esteem, relationship_satis)

Corr(regression)
```
##Regression
```{r}
model<-lm(relationship_satis ~ power + authenticity + Self_esteem, data = regression)

check_model(model)

model_summary(model)

tab_model(model)

plot_model(model,  type ="est",  show.values = TRUE, vline.color = "#1B191999", line.size = 1.5, dot.size = 2.5, colors = "blue") + theme_bruce()

```

